query friendships ($first: Int, $after: String) { 
  friendships (first: $first, after: $after) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        name
        handle
        profilePicture
      }
    }
  }
}