query Activities($latitude: Float!, $longitude: Float!, $filters: String, $saved: Boolean, $createdBy: ID, $page: Int){
  activities (latitude: $latitude, longitude: $longitude, filters: $filters, saved: $saved, createdBy: $createdBy, page: $page) {
    pk
    id
    saved
    name
    description
    alcoholPresent
    isNsfw
    minimumAge
    maximumAge
    handicapFriendly
    price
    distance
    media
    nextOccurrence
    location {
      address
      latitude
      longitude
    }
  }
}