query activity($pk: ID!){ 
  activity (pk: $pk) {
    pk
    id
    name
    media
    price
    duration
    description
    alcoholPresent
    isNsfw
    minimumAge
    maximumAge
    handicapFriendly
    upcomingDates {
      alwaysAvailable
      startDate
      endDate
    }
    nextOccurrence {
      alwaysAvailable
      startDate
      endDate
    }
    saved
    createdBy {
      id
    }
    location {
      name
      address
      latitude
      longitude
    }
  }
}