query Activities($latitude: Float!, $longitude: Float!, $filters: String, $saved: Boolean, $createdBy: Int){ 
  activities (latitude: $latitude, longitude: $longitude, filters: $filters, saved: $saved, createdBy: $createdBy) {
    pk
    id
    saved
    name
    description
    alcoholPresent
    isNsfw
    minimumAge
    maximumAge
    handicapFriendly
    price
    duration
    media
    nextOccurrence
    prevOccurrence
    location {
      address
      latitude
      longitude
    }
  }
}