query activity($pk: Int!){ 
  activity (pk: $pk) {
    pk
    id
    name
    media
    price
    duration
    description
    alcoholPresent
    isNsfw
    minimumAge
    maximumAge
    handicapFriendly
    nextOccurrence
    prevOccurrence
    saved
    location {
      address
      latitude
      longitude
    }
  }
}