query randomActivity($latitude: Float, $longitude: Float){ 
  randomActivity (latitude: $latitude, longitude: $longitude) {
    pk
    id
    name
    media
    price
    duration
    description
    alcoholPresent
    isNsfw
    minimumAge
    maximumAge
    handicapFriendly
    nextOccurrence
    prevOccurrence
    saved
    location {
      address
      latitude
      longitude
    }
  }
}