query getUser ($pk: ID) {
  user (pk: $pk) {
    settings {
      showAlcohol
      showNsfw
      handicapOnly
      newFriendEventNotification
      upcomingSavedEventNotification
    }
  }
}